# Generated by Django 4.1 on 2022-08-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='is_forExchange',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='is_forRent',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='is_forSale',
        ),
        migrations.AddField(
            model_name='apartment',
            name='kind',
            field=models.IntegerField(choices=[(1, 'اجاره'), (2, 'فروش'), (3, 'معاوضه')], default=1, verbose_name='مورد جهت'),
        ),
    ]
