# Generated by Django 4.1 on 2022-09-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='number',
            field=models.IntegerField(default=1, verbose_name='قطعه شماره'),
        ),
    ]
